export { KonfidantClient, openShare, DEFAULT_BASE_URL } from './client';
export { KonfidantApiError } from './errors';
export type {
  KonfidantClientOptions,
  ShareTextOptions,
  ShareTextResult,
  FileData,
  ShareFileOptions,
  ShareFileResult,
  FileUpload,
  CompleteFileUploadResult,
  OpenedShare,
  ApiShareTextResponse,
  ApiCreateFileResponse,
  ApiCompleteFileResponse,
  ListSharesResponse,
  ListSharesParams,
  Share,
  Pagination,
  KonfidantErrorBody,
} from './types';

// KNF1 primitives for advanced use (custom upload pipelines, streaming decryption, interop tests).
export {
  KNF_MAGIC,
  KNF_HEADER_SIZE,
  KNF_TAG_SIZE,
  KNF_KEY_SIZE,
  KNF_NONCE_PREFIX_SIZE,
  KNF_DEFAULT_CHUNK_SIZE,
  KNF_MIN_CHUNK_SIZE,
  KNF_MAX_CHUNK_SIZE,
  KNF_MAX_NAME_BYTES,
  KNF_MAX_MIME_BYTES,
  KnfError,
  KnfDecryptor,
  generateKey,
  encodeKey,
  decodeKey,
  encodeMetadata,
  ciphertextSize,
  maxFileCiphertextSize,
  maxTextCiphertextSize,
  hasValidHeader,
  bytesSource,
  blobSource,
  encrypt,
  encryptText,
  concat,
  decrypt,
  decodeText,
  buildShareUrl,
  parseShareFragment,
} from './knf';
export type { KnfKind, KnfMetadata, KnfDecrypted, KnfSource, EncryptOptions } from './knf';
